//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountTester {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountTester.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        internal static string CopyButton {
            get {
                return ResourceManager.GetString("CopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        internal static string ExportButton {
            get {
                return ResourceManager.GetString("ExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Logs :.
        /// </summary>
        internal static string LabelLogs {
            get {
                return ResourceManager.GetString("LabelLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langage.
        /// </summary>
        internal static string langageToolStripMenuItem {
            get {
                return ResourceManager.GetString("langageToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à null.
        /// </summary>
        internal static string nullValue {
            get {
                return ResourceManager.GetString("nullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Options.
        /// </summary>
        internal static string optionsToolStripMenuItem {
            get {
                return ResourceManager.GetString("optionsToolStripMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test report.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_1 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Passed tests.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_10 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restart.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_11 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_2 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internet.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_3 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Network drives.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_4 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Office version.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_5 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Office rights.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_6 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Printer.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_7 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tests finished..
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_8 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total time elapsed.
        /// </summary>
        internal static string RTBL_ExecutionSequentielle_9 {
            get {
                return ResourceManager.GetString("RTBL_ExecutionSequentielle_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - Status : Connected.
        /// </summary>
        internal static string RTBL_Internet_1 {
            get {
                return ResourceManager.GetString("RTBL_Internet_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à - Status : .
        /// </summary>
        internal static string RTBL_Internet_2 {
            get {
                return ResourceManager.GetString("RTBL_Internet_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Write refused.
        /// </summary>
        internal static string RTBL_NetworkStorageRightsTesting_1 {
            get {
                return ResourceManager.GetString("RTBL_NetworkStorageRightsTesting_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion error.
        /// </summary>
        internal static string RTBL_NetworkStorageRightsTesting_2 {
            get {
                return ResourceManager.GetString("RTBL_NetworkStorageRightsTesting_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Omitted.
        /// </summary>
        internal static string RTBL_NetworkStorageRightsTesting_3 {
            get {
                return ResourceManager.GetString("RTBL_NetworkStorageRightsTesting_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version not found.
        /// </summary>
        internal static string RTBL_OfficeVersionTesting_1 {
            get {
                return ResourceManager.GetString("RTBL_OfficeVersionTesting_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can create.
        /// </summary>
        internal static string RTBL_OfficeWRTesting_1 {
            get {
                return ResourceManager.GetString("RTBL_OfficeWRTesting_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can save.
        /// </summary>
        internal static string RTBL_OfficeWRTesting_2 {
            get {
                return ResourceManager.GetString("RTBL_OfficeWRTesting_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can read.
        /// </summary>
        internal static string RTBL_OfficeWRTesting_3 {
            get {
                return ResourceManager.GetString("RTBL_OfficeWRTesting_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can write.
        /// </summary>
        internal static string RTBL_OfficeWRTesting_4 {
            get {
                return ResourceManager.GetString("RTBL_OfficeWRTesting_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can delete.
        /// </summary>
        internal static string RTBL_OfficeWRTesting_5 {
            get {
                return ResourceManager.GetString("RTBL_OfficeWRTesting_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No printer found..
        /// </summary>
        internal static string RTBL_PrinterTesting_1 {
            get {
                return ResourceManager.GetString("RTBL_PrinterTesting_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not found.
        /// </summary>
        internal static string RTBL_PrinterTesting_2 {
            get {
                return ResourceManager.GetString("RTBL_PrinterTesting_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Location value not found in registry..
        /// </summary>
        internal static string RTBL_PrinterTesting_3 {
            get {
                return ResourceManager.GetString("RTBL_PrinterTesting_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registry key not found for printer..
        /// </summary>
        internal static string RTBL_PrinterTesting_4 {
            get {
                return ResourceManager.GetString("RTBL_PrinterTesting_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start.
        /// </summary>
        internal static string StartButton {
            get {
                return ResourceManager.GetString("StartButton", resourceCulture);
            }
        }
    }
}
